foris_dev/urls.py
from django.urls import path, include
from main_page import urls as main_page_urls
from lists import urls as lists_urls
from accounts import urls as accounts_urls
from rest_api.api_urls import router
from rest_api import api_urls
from the_elder_commands import urls as tec_urls

urlpatterns = [
    path("", include(main_page_urls)),
    path("lists/", include(lists_urls)),
    path("accounts/", include(accounts_urls)),
    path("api/", include(router.urls)),
    path("api/", include(api_urls)),
    path("the_elder_commands/", include(tec_urls)),
]

lists/urls.py
from django.urls import path
from lists import views


app_name = "lists"
urlpatterns = [
    path("", views.home_page, name="home"),
    path("new", views.new_list, name="new_list"),
    path("<int:list_id>/", views.view_list, name="view_list"),
    path("users/<str:email>/", views.my_lists, name="my_lists"),
    path("<int:list_id>/share", views.share, name="share"),
]

main_page/urls.py
from django.urls import path
from main_page import views


app_name = "main_page"

urlpatterns = [
    path("", views.home_page, name="home"),
    path("about_me", views.about_me, name="about_me"),
    path("contact", views.contact, name="contact"),
]

the_elder_commands/urls.py
from django.urls import path
from .views.home import home_view
from .views.skills import skills_view
from .views.items import items_view
from .views.spells import spells_view
from .views.other import other_view
from .views.plugins import plugins_view
from .views.commands import commands_view
from .views.commands_download import commands_download_view
from .views.commands_reset import commands_reset_view

app_name = "tec"

urlpatterns = [
    path("", home_view, name="home"),
    path("skills/", skills_view, name="skills"),
    path("items/", items_view, name="items"),
    path("spells/", spells_view, name="spells"),
    path("other/", other_view, name="other"),
    path("plugins/", plugins_view, name="plugins"),
    path("commands/", commands_view, name="commands"),
    path("commands/download", commands_download_view, name="commands_download"),
    path("commands/reset", commands_reset_view, name="commands_reset"),
]

accounts/models.py
from django.db import models
import uuid


class User(models.Model):
    email = models.EmailField(unique=True)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = "email"
    is_anonymous = False
    is_authenticated = True
    is_active = True


class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=55)

main_page/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from the_elder_commands.utils.check_recaptcha import check_recaptcha
from the_elder_commands.utils.messages_system import MessagesSystem
from django.conf import settings
from smtplib import SMTPException


def home_page(request):
    return render(request, "main_page/home.html")


def about_me(request):
    return render(request, "main_page/about_me.html")


def contact(request):
    messages = MessagesSystem(request)
    if request.method == "POST":

        send_contact_email(request)

        return redirect("main_page:contact")

    return render(request, "main_page/contact.html", {"messages": messages.pop_contact(),
                                                      "site_key": settings.RECAPTCHA_SITE_KEY})


@check_recaptcha("contact")
def send_contact_email(request):
    messages = MessagesSystem(request)
    try:
        email_message = f"Email: {request.POST.get('email')} \nMessage: {request.POST.get('message')}"
        send_mail(request.POST.get("subject"), email_message, "",
                  ["foris.dev@gmail.com"])
        messages.append_contact("Message was sent!")
    except SMTPException:
        messages.append_contact("Something went wrong! \nPlease try a different method of contact.")

the_elder_commands/views/home.py
from django.shortcuts import render


def home_view(request):
    return render(request, "the_elder_commands/home.html")

main_page/templates/main_page/about_me.html
{% extends "main_page/base.html" %}

{% block stylesheet %}
<link href="/static/main_page/about_me.css" rel="stylesheet">
{% endblock %}

{% block body %}
<div class="row">
    <div class="col my-5" id="about_me">
        <h3>About me:</h3>
        <p> I believe that the code should not only be written fast, but also with quality and readability in mind.
            That is why I do my best to follow agile and clean code principles.
            Following TDD rules allows me to write quality code and adds to the value that I bring to the team.<br><br>
            I think punctuality is very important, so I always do my best to deliver the task on time. Equally,
            good communication is vital. It is important to exchange information with other team member and to keep
            them informed if there are going to be any delays or issues that cannot be immediately resolved.
            It is equally important to resolve any issues arising without having to disturb others too much.</p>
    </div>
</div>
<div class="row">
    <div class="col-4 mx-auto my-5 " id="links">
        <h3>Links to my accounts:</h3>
        <ul>
            <li><a href="https://www.linkedin.com/in/Zglobicki-Pawel">LinkedIn</a></li>
            <li><a href="https://github.com/ForisTale">GitHub</a></li>
        </ul>
    </div>
</div>
{% endblock %}

main_page/templates/main_page/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Foris.dev</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="/static/main_page/base.css" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href=" {% static 'favicon.ico' %}">
    {% block stylesheet %}{% endblock %}
</head>
<body>
<div class="container text-info">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
    <div class="container-fluid">
        <a class="navbar-brand text-info" href="{% url 'main_page:home' %}">Foris.dev</a>
    <a class="text-info" href="{% url 'tec:home' %}">The Elder Commands</a>
        <a class="text-info" href="{% url 'main_page:contact' %}">Contact</a>
        <a class="text-info" href="{% url 'main_page:about_me' %}">About Me</a>
    </div>
</nav>

{% block body %}
{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
{% block script %}
{% endblock %}
</body>
</html>

main_page/templates/main_page/contact.html
{% extends "main_page/base.html" %}
{% block stylesheet %}
    <link href="/static/main_page/contact.css" rel="stylesheet">
{% endblock %}

{% block script %}
<script src="https://www.google.com/recaptcha/api.js"></script>
<script>
   function onSubmit() {
     let form = document.getElementById("id_contact_form");
     form.submit();
   }
 </script>
{% endblock %}

{% block body %}
    <div class="row row-separator"></div>
    {% for message in messages %}
        <div class="row messages">
            <div class="col-auto">
                <div class="alert alert-primary alert-dismissible fade show" role="alert">
                    <h4><strong>{{ message }}</strong></h4>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        </div>
    {% endfor %}
    <form action="{% url 'main_page:contact' %}" method="post" id="id_contact_form">
    <div class="row">
        <div class="col-4">
            <label for="id_subject">Subject:</label>
            <input id="id_subject" class="form-control" name="subject" required>
            <div class="row row-separator"></div>
            <label for="id_email">Email:</label>
            <input id="id_email" name="email" placeholder="Optional" class="form-control">
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label for="id_message">Message:</label>
            <textarea name="message" class="form-control" id="id_message" rows="10" required></textarea>
        </div>
    </div>
    <div class="row row-separator"></div>
    <div class="row">
        <div class="col-sm-5 col-12"></div>
        <div class="col-sm-2 col-12">
            <button class="btn btn-dark text-info g-recaptcha" id="id_submit" data-sitekey ="{{ site_key }}"
                    data-callback="onSubmit" data-action="submit">Send</button>
            {% csrf_token %}
        </div>
    </div>
    </form>
{% endblock %}

main_page/templates/main_page/home.html
{% extends "main_page/base.html" %}

{% block body %}
<div class="row my-5">
    <div class="col-md-12 my-5 mx-auto">
        <h2>Purpose of this website:</h2>
        <p>This site was created to demonstrate some of my django projects.<br>
        If you want to know more about my projects visit "About Me" page, where you can find link to my accounts.</p>
    </div>
</div>
<div class="row my-5">
    <div class="col-md-12 mx-auto">
        <h2><a class="text-info" href="{% url 'tec:home' %}">The Elder Commands</a></h2>
        <p>
            It generate console commands for skills, items, spells, etc. for base game and mods. <br>
            And lets you add new mods to the database.
        </p>
    </div>
</div>
<div class="row my-5">
<div class="col-md-12 mx-auto">
    <p>My projects are deployed using Ansible and under CI using Jenkins.</p>
</div>
</div>
{% endblock %}