foris_dev/urls.py
from django.urls import path, include
from main_page import urls as main_page_urls
from lists import urls as lists_urls
from accounts import urls as accounts_urls
from rest_api.api_urls import router
from rest_api import api_urls
from the_elder_commands import urls as tec_urls

urlpatterns = [
    path("", include(main_page_urls)),
    path("lists/", include(lists_urls)),
    path("accounts/", include(accounts_urls)),
    path("api/", include(router.urls)),
    path("api/", include(api_urls)),
    path("the_elder_commands/", include(tec_urls)),
]

lists/urls.py
from django.urls import path
from lists import views


app_name = "lists"
urlpatterns = [
    path("", views.home_page, name="home"),
    path("new", views.new_list, name="new_list"),
    path("<int:list_id>/", views.view_list, name="view_list"),
    path("users/<str:email>/", views.my_lists, name="my_lists"),
    path("<int:list_id>/share", views.share, name="share"),
]

main_page/urls.py
from django.urls import path
from main_page import views


app_name = "main_page"

urlpatterns = [
    path("", views.home_page, name="home"),
    path("about_me", views.about_me, name="about_me"),
    path("contact", views.contact, name="contact"),
]

the_elder_commands/urls.py
from django.urls import path
from .views.home import home_view
from .views.skills import skills_view
from .views.items import items_view
from .views.spells import spells_view
from .views.other import other_view
from .views.plugins import plugins_view
from .views.commands import commands_view
from .views.commands_download import commands_download_view
from .views.commands_reset import commands_reset_view

app_name = "tec"

urlpatterns = [
    path("", home_view, name="home"),
    path("skills/", skills_view, name="skills"),
    path("items/", items_view, name="items"),
    path("spells/", spells_view, name="spells"),
    path("other/", other_view, name="other"),
    path("plugins/", plugins_view, name="plugins"),
    path("commands/", commands_view, name="commands"),
    path("commands/download", commands_download_view, name="commands_download"),
    path("commands/reset", commands_reset_view, name="commands_reset"),
]

the_elder_commands/forms/selected_plugin_form.py
from the_elder_commands.inventory.messages import INCORRECT_LOAD_ORDER, NO_PLUGIN_SELECTED
from the_elder_commands.models import Plugins
from the_elder_commands.utils.selected_plugins import SelectedPlugins
import json


class SelectedPluginsForm:
    def __init__(self, request):
        self.request = request
        self.errors = []
        self.data = self.get_data(request)

        self.check_data_not_empty()
        self.clean_load_order()
        if self.is_valid():
            self.collect_selected()

    def clean_load_order(self):
        for plugin in self.data:
            load_order = plugin.get("load_order", "")
            length = len(load_order)
            if length == 2 and not self.is_esl(plugin):
                if load_order.isalnum():
                    continue
            elif length == 5 and self.is_esl(plugin):
                if load_order.isalnum():
                    if load_order[:2] in ["FE", "FF"]:
                        continue

            self.errors.append(INCORRECT_LOAD_ORDER)

    def is_esl(self, plugin):
        variant = self.split_variant(plugin)
        return bool(variant[2])

    def is_valid(self):
        return self.errors == []

    def collect_selected(self):
        collected = []
        for plugin in self.data:
            usable_name = plugin.get("name")
            variant = self.split_variant(plugin)
            collected.append({
                "name": self.get_name(usable_name),
                "usable_name": usable_name,
                "version": variant[0],
                "language": variant[1],
                "is_esl": self.is_esl(plugin),
                "load_order": plugin.get("load_order")
            })
        SelectedPlugins(self.request).set(collected)

    @staticmethod
    def split_variant(plugin):
        plugin_variants = plugin.get("variant", "")
        variant = plugin_variants.split("&")
        return variant

    @staticmethod
    def get_name(usable_name):
        plugin = Plugins.objects.get(usable_name=usable_name)
        return plugin.name

    @staticmethod
    def get_data(request):
        post = request.POST.get("selected_plugins")
        converted_post = json.loads(post)
        return converted_post

    def check_data_not_empty(self):
        if not self.data:
            self.errors.append(NO_PLUGIN_SELECTED)

the_elder_commands/views/commands.py
from django.shortcuts import render

from the_elder_commands.utils.commands import Commands


def commands_view(request):
    commands = Commands(request).get_commands()
    return render(request, "the_elder_commands/commands.html", {"active": "commands",
                                                                "commands": commands})

the_elder_commands/views/commands_download.py
from io import BytesIO

from django.http import FileResponse

from the_elder_commands.utils.commands import Commands


def commands_download_view(request):
    commands = Commands(request).get_commands()
    content = "\n".join(commands)
    encoded = content.encode("utf-8")
    file = BytesIO(encoded)
    return FileResponse(file, as_attachment=True, filename="TEC_Commands.txt")

the_elder_commands/views/commands_reset.py
from django.shortcuts import redirect

from the_elder_commands.utils.chosen import ChosenItems, ChosenSpells, ChosenOther
from the_elder_commands.utils.commands import Commands
from the_elder_commands.utils.defauld_skills_race_update import default_skills_race_update
from the_elder_commands.utils.skills import Skills


def commands_reset_view(request):
    reset_skills(request)
    reset_chosen(request)
    reset_commands(request)
    return redirect("tec:commands")


def reset_skills(request):
    skills = Skills(request)
    race = skills.get_race()
    skills_after_reset = default_skills_race_update(race)
    skills.save_skills(skills_after_reset)
    skills.save_fill_skills(None)


def reset_commands(request):
    commands = Commands(request)
    commands.set_skills([])
    commands.set_items({})
    commands.set_spells({})
    commands.set_other({})


def reset_chosen(request):
    ChosenItems(request).set({})
    ChosenSpells(request).set({})
    ChosenOther(request).set({})

the_elder_commands/views/home.py
from django.shortcuts import render


def home_view(request):
    return render(request, "the_elder_commands/home.html")

the_elder_commands/views/items.py
from django.http import JsonResponse
from django.shortcuts import redirect, render

from the_elder_commands.inventory.messages import NO_PLUGIN_SELECTED_ERROR_MESSAGE, COMMANDS_SUCCESS_MESSAGE, \
    ITEMS_COMMANDS_POST_EMPTY_MESSAGE
from the_elder_commands.utils.chosen import ChosenItems
from the_elder_commands.utils.commands import Commands
from the_elder_commands.utils.convert_value_post import convert_value_post
from the_elder_commands.utils.messages_system import MessagesSystem
from the_elder_commands.utils.selected_plugins import SelectedPlugins


def items_view(request):
    if not SelectedPlugins(request).exist():
        MessagesSystem(request).append_plugin(NO_PLUGIN_SELECTED_ERROR_MESSAGE)
        return redirect("tec:plugins")

    if request.method == "POST":
        items = convert_value_post(request)
        ChosenItems(request).set(items)
        Commands(request).set_items(items)
        if items:
            message = COMMANDS_SUCCESS_MESSAGE
        else:
            message = ITEMS_COMMANDS_POST_EMPTY_MESSAGE
        return JsonResponse({"message": message})

    messages = MessagesSystem(request).pop_items()
    return render(request, "the_elder_commands/items.html", {"active": "items", "messages": messages})

the_elder_commands/views/other.py
from django.http import JsonResponse
from django.shortcuts import redirect, render

from the_elder_commands.inventory.messages import NO_PLUGIN_SELECTED_ERROR_MESSAGE, COMMANDS_SUCCESS_MESSAGE, \
    OTHER_COMMANDS_POST_EMTPY_MESSAGE
from the_elder_commands.utils.chosen import ChosenOther
from the_elder_commands.utils.commands import Commands
from the_elder_commands.utils.convert_value_post import convert_value_post
from the_elder_commands.utils.messages_system import MessagesSystem
from the_elder_commands.utils.selected_plugins import SelectedPlugins


def other_view(request):
    if not SelectedPlugins(request).exist():
        MessagesSystem(request).append_plugin(NO_PLUGIN_SELECTED_ERROR_MESSAGE)
        return redirect("tec:plugins")

    if request.method == "POST":
        variety = convert_value_post(request)
        ChosenOther(request).set(variety)
        Commands(request).set_other(variety)
        if variety:
            message = COMMANDS_SUCCESS_MESSAGE
        else:
            message = OTHER_COMMANDS_POST_EMTPY_MESSAGE
        return JsonResponse({"message": message})

    messages = MessagesSystem(request).pop_other()
    chosen = ChosenOther(request).get()
    return render(request, "the_elder_commands/other.html", {"active": "other", "chosen": chosen,
                                                             "messages": messages})

the_elder_commands/views/plugins.py
import os

from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import redirect, render

from the_elder_commands.forms.add_plugins_form import AddPluginsForm
from the_elder_commands.forms.selected_plugin_form import SelectedPluginsForm
from the_elder_commands.inventory.messages import ADD_PLUGIN_SUCCESS_MESSAGE, SELECTED_PLUGINS_SUCCESS
from the_elder_commands.services.plugins import PluginsService
from the_elder_commands.utils.check_recaptcha import check_recaptcha
from the_elder_commands.utils.messages_system import MessagesSystem
from the_elder_commands.utils.selected_plugins import SelectedPlugins


def plugins_view(request):
    if request.method == "POST":
        if "add_plugin" in request.POST:
            manage_add_plugin_post(request)
            return redirect("tec:plugins")
        elif "unselect" in request.POST:
            manage_unselect_post(request)
            return redirect("tec:plugins")
        if "selected_plugins" in request.POST:
            manage_selected_post(request)
            return JsonResponse({})

    service = PluginsService(request)
    messages = MessagesSystem(request).pop_plugins()
    zedit_data = get_zedit_data()
    return render(request, "the_elder_commands/plugins.html", {"active": "plugins", "service": service,
                                                               "messages": messages, "zedit": zedit_data,
                                                               "site_key": settings.RECAPTCHA_SITE_KEY})


@check_recaptcha("plugin")
def manage_add_plugin_post(request):
    form = AddPluginsForm(request)
    if form.is_valid():
        MessagesSystem(request).append_plugin(ADD_PLUGIN_SUCCESS_MESSAGE)
    else:
        MessagesSystem(request).append_plugin(form.errors)


def manage_selected_post(request):
    form = SelectedPluginsForm(request)
    if form.is_valid():
        MessagesSystem(request).append_plugin(SELECTED_PLUGINS_SUCCESS)
    else:
        MessagesSystem(request).append_plugin(form.errors)


def manage_unselect_post(request):
    selected = SelectedPlugins(request)
    selected.unselect()


def get_zedit_data():
    path = os.getcwd()
    path = os.path.join(path, "the_elder_commands", "script_for_zEdit.js")
    with open(path, "r") as file:
        return file.read()

the_elder_commands/views/skills.py
from django.shortcuts import redirect, render

from the_elder_commands.forms.validate_skills import ValidateSkills
from the_elder_commands.inventory.messages import COMMANDS_SUCCESS_MESSAGE
from the_elder_commands.services.skills import SkillsService
from the_elder_commands.utils.commands import Commands
from the_elder_commands.utils.defauld_skills_race_update import default_skills_race_update
from the_elder_commands.utils.messages_system import MessagesSystem
from the_elder_commands.utils.skills import Skills


def skills_view(request):
    if request.method == "POST":
        if "race" in request.POST:
            manage_race_post(request)
        else:
            manage_skills_post(request)
        return redirect("tec:skills")

    message = MessagesSystem(request).pop_skills()
    service = SkillsService(request)
    Commands(request).set_skills(service.commands)
    return render(request, "the_elder_commands/skills.html", {"service": service, "messages": message,
                                                              "active": "skills"})


def manage_race_post(request):
    race = request.POST.get("race")
    reset_skills = default_skills_race_update(race)
    skills = Skills(request)
    skills.save_race(race)
    skills.save_skills(reset_skills)
    skills.save_fill_skills(None)


def manage_skills_post(request):
    form = ValidateSkills(request)
    if form.is_valid():
        form.save()
        MessagesSystem(request).append_skills(COMMANDS_SUCCESS_MESSAGE)
    else:
        MessagesSystem(request).append_skills(form.errors)

the_elder_commands/views/spells.py
from django.http import JsonResponse
from django.shortcuts import redirect, render

from the_elder_commands.inventory.messages import NO_PLUGIN_SELECTED_ERROR_MESSAGE, COMMANDS_SUCCESS_MESSAGE, \
    SPELLS_COMMANDS_POST_EMPTY_MESSAGE
from the_elder_commands.utils.chosen import ChosenSpells
from the_elder_commands.utils.commands import Commands
from the_elder_commands.utils.convert_value_post import convert_value_post
from the_elder_commands.utils.messages_system import MessagesSystem
from the_elder_commands.utils.selected_plugins import SelectedPlugins


def spells_view(request):
    if not SelectedPlugins(request).exist():
        MessagesSystem(request).append_plugin(NO_PLUGIN_SELECTED_ERROR_MESSAGE)
        return redirect("tec:plugins")

    if request.method == "POST":
        spells = convert_value_post(request)
        ChosenSpells(request).set(spells)
        Commands(request).set_spells(spells)
        if spells:
            message = COMMANDS_SUCCESS_MESSAGE
        else:
            message = SPELLS_COMMANDS_POST_EMPTY_MESSAGE
        return JsonResponse({"message": message})

    message = MessagesSystem(request).pop_spells()
    return render(request, "the_elder_commands/spells.html", {"active": "spells", "messages": message})

the_elder_commands/templates/the_elder_commands/base.html
{% load static %}
{% load tec_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="/static/the_elder_commands/base.css" rel="stylesheet">
    <link rel="shortcut icon" href=" {% static 'favicon.ico' %}">
    <title>The Elder Commands</title>
    {% block head %}
    {% endblock %}
</head>
<body>
<div class="container-fluid">
<ul class="nav nav-pills bg-dark justify-content-around">
    <li class="nav-item">
        <a class="nav-link header-link text-info " href="{% url 'main_page:home' %}">Foris.dev</a>
    </li>
    {% for category in main_categories %}
    <li class="nav-item">
        {% with "tec:"|addstr:category as address_url %}
        {% if active == category %}
            <a class="nav-link header-link active" href="{% url address_url %}">{{ category|title }}</a>
        {% else %}
            <a class="nav-link header-link text-info" href="{% url address_url %}">{{ category|title }}</a>
        {% endif %}
        {% endwith %}
    </li>
    {% endfor %}
</ul>
<div class="row row-separator"></div>
{% block body %}
{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
{% block scripts %}
{% endblock %}
</body>
</html>

the_elder_commands/templates/the_elder_commands/commands.html
{% extends "the_elder_commands/base.html" %}

{% block body %}
<div class="row row-separator"></div>
<div class="row">
    <div class="col-md-4 col-12">
        <label><a class="btn-dark text-info btn-lg reset" href="{% url 'tec:commands_reset' %}"
        >Reset All Commands</a></label>
    </div>
    <div class="col-md-4 col-12">
        <label><a class="btn-dark text-info btn-lg download" href="{% url 'tec:commands_download' %}"
        >Download Commands</a></label>
    </div>
</div>
<div class="row row-separator"></div>

<div class="row row-separator">
<div class="col-md-2 col-12">
    <table class="table table-dark text-info" id="id_commands_list">
        <thead>
        <tr>
            <th>Commands List:</th>
        </tr>
        </thead>
        <tbody>
        {% for command in commands %}
        <tr>
            <td>{{ command }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

</div>

{% endblock %}

the_elder_commands/templates/the_elder_commands/home.html
{% extends "the_elder_commands/base.html" %}

{% block body %}
<div class="row row-separator"></div>
<div class="row">
    <div class="col-12 col-lg-4"></div>
    <div class="col-12 col-lg-4">
        <h1>The Elder Commands</h1>
        <p>This is a website I created to make it easier to play Skyrim with different skills and mods.<br>
        You can easily add mods to the database, just follow the instructions on the plugins page.</p>
        <br>
        <h4>Skills</h4>
        <p>Allows to generate skills commands. Selecting "Fill skills to desired level?" to raise all skills till
        they meet desired level. Additionally selecting multiplier will raise given skill X times more often. </p>
        <br>
        <h4>Items & Spells & Other</h4>
        <p>Generate commands from selected plugins. To save any changed in tables you need to generate
            commands. <br>
            For adding spells, my advice is to use spell books if possible, as spells often have few versions. Editor Id
            may help to understand intended usage.<br>
        </p>
        <br>
        <h4>Plugins</h4>
        <p>Select plugins you want to use, get load order from you mod manager. If you want to add mod, select "Add
            Plugin" and follow the instructions.</p>
        <br>
        <h4>Commands</h4>
        <p>Here you can copy or download commands, as well as clear all commands.
            Easy way to use commands is to download them and paste to folder with Skyrim.exe.
            Then in game use command: bat FileName</p>
        <br>
        <h4>Contact</h4>
        <p>If you have any questions or suggestions please contact me by using this page:
            <a href="{% url 'main_page:contact' %}">Contact</a></p>
    </div>
    <div class="col-12 col-lg-4"></div>
</div>
{% endblock %}

the_elder_commands/templates/the_elder_commands/items.html
{% extends "the_elder_commands/base.html" %}
{% load tec_extras %}

{% block head %}
<link href="/static/the_elder_commands/dataTables.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
{% endblock %}

{% block scripts %}
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8"
        src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
<script src="/static/the_elder_commands/TEC.js"></script>
<script src="/static/the_elder_commands/TECItems.js"></script>
<script>$(document).ready( function () { new TECItems({url: "{% url 'tec:items' %}",
                                                       messages: {{ messages|safe }}}) });</script>
{% endblock %}

{% block body %}


<div class="row">
<div class="col">
    <ul class="nav nav-tabs bg-dark justify-content-around" id="id_items_categories" role="tablist">
        {% for category in items_categories %}
        <li class="nav-item">
            <a class="nav-link text-info {% if category == "weapons" %}active show{% endif %}"
               id="id_{{ category|strip_space }}" data-toggle="tab" role="tab"
               href="#id_{{ category|strip_space }}_panel" aria-controls="id_{{ category|strip_space }}_panel"
               aria-selected="{% if category == "weapons" %}true{% else %}false{% endif %}">{{ category|title }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
</div>

<div class="row row-separator"></div>

<div class="tab-content">
<div class="tab-pane fade show active" id="id_weapons_panel" role="tabpanel" aria-labelledby="id_weapons">
    <div class="row">
    <div class="col">
        <table class="table table-dark text-info" id="id_weapons_table">
            <thead>
            <tr>
                <th>Quantity</th>
                <th>Item name</th>
                <th>Damage</th>
                <th>Value</th>
                <th>Type</th>
                <th>Weight</th>
                <th>Plugin</th>
                <th>Editor ID</th>
                <th>Form ID</th>
                <th>Magic</th>
            </tr>
            </thead>
            <tbody id="id_weapons_tbody">
            </tbody>
        </table>
    </div>
    </div>
</div>
<div class="tab-pane fade" id="id_armors_panel" role="tabpanel" aria-labelledby="id_armors">
    <div class="row">
    <div class="col">
        <table class="table table-dark text-info" id="id_armors_table">
            <thead>
            <tr>
                <th>Quantity</th>
                <th>Item name</th>
                <th>Armor</th>
                <th>Type</th>
                <th>Value</th>
                <th>Weight</th>
                <th>Plugin</th>
                <th>Editor ID</th>
                <th>Form ID</th>
                <th>Magic</th>
            </tr>
            </thead>
            <tbody id="id_armors_tbody">
            </tbody>
        </table>
    </div>
    </div>
</div>
<div class="tab-pane fade" id="id_ammo_panel" role="tabpanel" aria-labelledby="id_ammo">
    <div class="row">
    <div class="col">
        <table class="table table-dark text-info" id="id_ammo_table">
            <thead>
            <tr>
                <th>Quantity</th>
                <th>Item name</th>
                <th>Damage</th>
                <th>Value</th>
                <th>Plugin</th>
                <th>Editor ID</th>
                <th>Form ID</th>
            </tr>
            </thead>
            <tbody id="id_ammo_tbody">
            </tbody>
        </table>
    </div>
    </div>
</div>
<div class="tab-pane fade" id="id_books_panel" role="tabpanel" aria-labelledby="id_books">
    <div class="row">
    <div class="col">
        <table class="table table-dark text-info" id="id_books_table">
            <thead>
            <tr>
                <th>Quantity</th>
                <th>Item name</th>
                <th>Value</th>
                <th>Weight</th>
                <th>Plugin</th>
                <th>Editor ID</th>
                <th>Form ID</th>
            </tr>
            </thead>
            <tbody id="id_books_tbody">
            </tbody>
        </table>
    </div>
    </div>
</div>
<div class="tab-pane fade" id="id_ingredients_panel" role="tabpanel" aria-labelledby="id_ingredients">
    <div class="row">
    <div class="col">
        <table class="table table-dark text-info" id="id_ingredients_table">
            <thead>
            <tr>
                <th>Quantity</th>
                <th>Item name</th>
                <th>Value</th>
                <th>Weight</th>
                <th>Plugin</th>
                <th>Editor ID</th>
                <th>Form ID</th>
                <th>Effects</th>
            </tr>
            </thead>
            <tbody id="id_ingredients_tbody">
            </tbody>
        </table>
    </div>
    </div>
</div>
<div class="tab-pane fade" id="id_alchemy_panel" role="tabpanel" aria-labelledby="id_alchemy">
    <div class="row">
    <div class="col">
        <table class="table table-dark text-info" id="id_alchemy_table">
            <thead>
            <tr>
                <th>Quantity</th>
                <th>Item name</th>
                <th>Value</th>
                <th>Weight</th>
                <th>Plugin</th>
                <th>Editor ID</th>
                <th>Form ID</th>
                <th>Effects</th>
            </tr>
            </thead>
            <tbody id="id_alchemy_tbody">
            </tbody>
        </table>
    </div>
    </div>
</div>
<div class="tab-pane fade" id="id_scrolls_panel" role="tabpanel" aria-labelledby="id_scrolls">
    <div class="row">
    <div class="col">
        <table class="table table-dark text-info" id="id_scrolls_table">
            <thead>
            <tr>
                <th>Quantity</th>
                <th>Item name</th>
                <th>Value</th>
                <th>Weight</th>
                <th>Plugin</th>
                <th>Editor ID</th>
                <th>Form ID</th>
                <th>Effects</th>
            </tr>
            </thead>
            <tbody id="id_scrolls_tbody">
            </tbody>
        </table>
    </div>
    </div>
</div>
<div class="tab-pane fade" id="id_soulgems_panel" role="tabpanel" aria-labelledby="id_soulgems">
    <div class="row">
    <div class="col">
        <table class="table table-dark text-info" id="id_soulgems_table">
            <thead>
            <tr>
                <th>Quantity</th>
                <th>Item name</th>
                <th>Value</th>
                <th>Weight</th>
                <th>Plugin</th>
                <th>Editor ID</th>
                <th>Form ID</th>
            </tr>
            </thead>
            <tbody id="id_soulgems_tbody">
            </tbody>
        </table>
    </div>
    </div>
</div>
<div class="tab-pane fade" id="id_keys_panel" role="tabpanel" aria-labelledby="id_keys">
    <div class="row">
    <div class="col">
        <table class="table table-dark text-info" id="id_keys_table">
            <thead>
            <tr>
                <th>Quantity</th>
                <th>Item name</th>
                <th>Value</th>
                <th>Weight</th>
                <th>Plugin</th>
                <th>Editor ID</th>
                <th>Form ID</th>
            </tr>
            </thead>
            <tbody id="id_keys_tbody">
            </tbody>
        </table>
    </div>
    </div>
</div>
<div class="tab-pane fade" id="id_miscellaneous_panel" role="tabpanel" aria-labelledby="id_miscellaneous">
    <div class="row">
    <div class="col">
        <table class="table table-dark text-info" id="id_miscellaneous_table">
            <thead>
            <tr>
                <th>Quantity</th>
                <th>Item name</th>
                <th>Value</th>
                <th>Weight</th>
                <th>Plugin</th>
                <th>Editor ID</th>
                <th>Form ID</th>
            </tr>
            </thead>
            <tbody id="id_miscellaneous_tbody">
            </tbody>
        </table>
    </div>
    </div>
</div>
</div>

{% csrf_token %}
{% endblock %}