accounts/urls.py
from django.urls import path
from accounts import views


app_name = "accounts"
urlpatterns = (
    path("send_login_email", views.send_login_email, name="send_login_email"),
    path("login", views.login, name="login"),
    path("logout", views.logout_view, name="logout"),
)

foris_dev/urls.py
from django.urls import path, include
from main_page import urls as main_page_urls
from lists import urls as lists_urls
from accounts import urls as accounts_urls
from rest_api.api_urls import router
from rest_api import api_urls
from the_elder_commands import urls as tec_urls

urlpatterns = [
    path("", include(main_page_urls)),
    path("lists/", include(lists_urls)),
    path("accounts/", include(accounts_urls)),
    path("api/", include(router.urls)),
    path("api/", include(api_urls)),
    path("the_elder_commands/", include(tec_urls)),
]

lists/urls.py
from django.urls import path
from lists import views


app_name = "lists"
urlpatterns = [
    path("", views.home_page, name="home"),
    path("new", views.new_list, name="new_list"),
    path("<int:list_id>/", views.view_list, name="view_list"),
    path("users/<str:email>/", views.my_lists, name="my_lists"),
    path("<int:list_id>/share", views.share, name="share"),
]

main_page/urls.py
from django.urls import path
from main_page import views


app_name = "main_page"

urlpatterns = [
    path("", views.home_page, name="home"),
    path("about_me", views.about_me, name="about_me"),
    path("contact", views.contact, name="contact"),
]

accounts/models.py
from django.db import models
import uuid


class User(models.Model):
    email = models.EmailField(unique=True)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = "email"
    is_anonymous = False
    is_authenticated = True
    is_active = True


class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=55)

lists/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings


class List(models.Model):

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE)
    shared_with = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="shared_list")

    @property
    def name(self):
        return self.item_set.first().text

    def get_absolute_url(self):
        return reverse("lists:view_list", args=[self.id])

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_.get_absolute_url()


class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

    class Meta:
        ordering = ("id",)
        unique_together = ("list", "text")

    def __str__(self):
        return self.text

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError
from lists.models import Item, List

EMPTY_ITEM_ERROR = "You can't have an empty list item."
DUPLICATE_ITEM_ERROR = "You've already got this in your list."


class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ("text",)
        widgets = {
            "text": forms.fields.TextInput(attrs={
                "placeholder": "Enter a To-Do item.",
                "class": "form-control input-lg",
            }),
        }
        error_messages = {
            "text": {"required": EMPTY_ITEM_ERROR}
        }


class NewListForm(ItemForm):

    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(first_item_text=self.cleaned_data["text"], owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data["text"])


class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {"text": [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

lists/views.py
from django.shortcuts import redirect, render
from lists.models import List
from lists.forms import ItemForm, ExistingListItemForm, NewListForm
from django.contrib.auth import get_user_model

USER_DONT_EXISTS_ERROR = "You can't share list with non exists user."
User = get_user_model()


def home_page(request):
    return render(request, "lists/home.html", {"form": ItemForm()})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == "POST":
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, "lists/list.html", {"list": list_, "form": form})


def new_list(request):
    form = NewListForm(data=request.POST)
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(str(list_))
    return render(request, "lists/home.html", {"form": form})


def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, "lists/my_lists.html", {"owner": owner})


def share(request, list_id):
    list_ = List.objects.get(id=list_id)
    email = request.POST["sharee"]
    try:
        user = User.objects.get(email=email)
        list_.shared_with.add(user)
        return redirect(list_)
    except User.DoesNotExist:
        user_error = USER_DONT_EXISTS_ERROR

    return render(request, "lists/list.html", {"list": list_, "user_error": user_error})

the_elder_commands/views/home.py
from django.shortcuts import render


def home_view(request):
    return render(request, "the_elder_commands/home.html")

lists/templates/lists/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To-Do List</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="/static/base.css" rel="stylesheet">
</head>
<body>
<div class="container">

<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main_page:home' %}">Foris.dev</a>
        <a class="navbar-brand" href="{% url 'lists:home' %}">Superlists</a>
        {% if user.email %}
        <ul class="nav navbar-nav navbar-left">
            <li><a href="{% url "lists:my_lists" user.email %}">My lists</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="navbar-text">Logged is as {{ user.email }}</li>
            <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
        </ul>
        {% else %}
        <form class="navbar-form navbar-right" method="POST"
              action="{% url 'accounts:send_login_email' %}">
            <label for="id_email">Enter email to log in:</label>
            <input class="form-control" name="email" id="id_email" type="email" />
            {% csrf_token %}
        </form>
        {% endif %}
    </div>
</nav>

{% if messages %}
<div class="row">
    <div class="col-md-8">
        {% for message in messages %}
            {% if message.level_tag == "success" %}
            <div class="alert alert-success">{{ message }}</div>
            {% else %}
            <div class="alert alert-warning">{{ message }}</div>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endif %}


<div class="row">
    <div class="col-md-12 jumbotron">
        <div class="text-center">
            <h1>
                {% block header_text %}{% endblock %}
            </h1>
            {% block list_form %}
            <form id="id_item_form" method="POST" action="{% block form_action %}{% endblock %}">
                {{ form.text }}
                {% csrf_token %}
                <div class="form-group has-error">
                    <div class="help-block">
                        {% if form.errors %}
                            {{ form.text.errors }}
                        {% endif %}
                    </div>
                </div>
            </form>
            {% endblock %}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-auto">
        {% block table %}
        {% endblock %}
    </div>
</div>

<div class="row">
    <div class="col-md-auto">
        {% block extra_content %}
        {% endblock %}
    </div>
</div>

</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="/static/list.js"></script>

{% block scripts %}
<script>
    $(document).ready(function () {
        window.Superlists.initialize();
    });
</script>
{% endblock %}

</body>
</html>

lists/templates/lists/home.html
{% extends "lists/base.html" %}
{% block header_text %}Start a new To-Do list.{% endblock %}
{% block form_action %}{% url "lists:new_list" %}{% endblock %}

lists/templates/lists/list.html
{% extends "lists/base.html" %}
{% block header_text %}Your To-Do list.{% endblock %}
{% block form_action %}{% url "lists:view_list" list.id %}{% endblock %}

{% block table %}
<table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
    <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
    {% endfor %}
</table>
<div class="row">
    <div class="col-auto">
        <h6>List shared with:</h6>
        <ul>
            {% for item in list.shared_with.all %}
            <li class="list-sharee">{{ item.email }}</li>
            {% endfor %}
        </ul>
        <p id="id_list_owner">List owner: {{ list.owner.email }}</p>
    </div>

        <div class="col-auto">
            <form id="id_share_form" method="POST" action="{% url 'lists:share' list.id %}">
                <label for="sharee">Share this list with your friend!</label>
                <input name="sharee" id="sharee" placeholder="your-friend@example.com" type="email">
                {% csrf_token %}
            </form>
            {% if user_error %}
            <div class="has-error">
                <h6>{{ user_error }}</h6>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
    $(document).ready(function () {
        window.Superlists.initialize({
            listApiUrl: "{% url 'list-detail' list.id %}",
            itemsApiUrl: "{% url 'item-list' %}",
            listId: {{ list.id }},
        });
    });
    </script>
{% endblock %}

lists/templates/lists/my_lists.html
{% extends "lists/base.html" %}
{% block header_text %}My Lists{% endblock %}
{% block list_form %}{% endblock %}

{% block extra_content %}
    <h2>{{ owner.email }}'s lists</h2>
    <ul>
        {% for list in owner.list_set.all %}
            <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
        {% endfor %}
    </ul>
    <h2>List shared by other users:</h2>
    <ul>
        {% for list in owner.shared_list.all %}
            <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
            <p>List owner: {{ list.owner.email }}</p>
        {% endfor %}
    </ul>
{% endblock %}